
version: "3.5"

# External network
networks:
    caddyweb:
        external: true

services:

    # Nuxt frontend app
    quasar:
        build: ./frontend/
        ports:
            - "${PORT}:${PORT}"
        environment:
            - url=${ORIGIN_URL}
        volumes:
            - ./frontend:/var/lib/frontend
        command:
            bash -c "cd dist/ssr/ && PORT=${PORT} npm run start"
        env_file:
            - ./env/.env.prod
        networks:
            - caddyweb